version: "3.2"
services:
  postgres:
    image: postgres:12
    volumes:
      - /tmp/postgres-backup/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
